"""Pipeline orchestrator: chains Source → Filter → Enrich → Render.

Run modes:
  --dry-run     Skip source adapter, use synthetic sample data
  --since DATE  Override the fetch window (ISO 8601, default: 24 hours ago)
  --limit N     Cap the number of incidents written (default: unlimited)

Outputs Markdown incident files into the incidents/ directory.
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import List

from scripts.config_loader import load_taxonomy, load_watchlist
from scripts.filter_engine import WatchlistFilterEngine
from scripts.enrich_rules import RuleBasedEnricher
from scripts.interfaces import (
    EnrichPipe,
    FilterEngine,
    Incident,
    RawItem,
    RenderAdapter,
    SourceAdapter,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
INCIDENTS_DIR = REPO_ROOT / "incidents"

# Characters allowed in a safe filename derived from an incident_id.
_SAFE_ID_RE = re.compile(r"^[a-zA-Z0-9_-]+$")


class MarkdownRenderAdapter:
    """Writes one Markdown file per incident with YAML frontmatter.

    Guards against path-traversal by rejecting incident IDs that contain
    directory separators or parent-directory sequences.
    """

    def render(self, incidents: List[Incident]) -> dict[str, str]:
        INCIDENTS_DIR.mkdir(parents=True, exist_ok=True)
        outputs: dict[str, str] = {}
        for inc in incidents:
            safe_id = self._sanitize_id(inc.incident_id)
            filename = f"{safe_id}.md"
            path = INCIDENTS_DIR / filename
            # Defensive: ensure resolved path stays inside INCIDENTS_DIR
            if not str(path.resolve()).startswith(str(INCIDENTS_DIR.resolve())):
                raise ValueError(f"Incident ID resolves outside target dir: {inc.incident_id}")
            content = self._render_one(inc)
            path.write_text(content, encoding="utf-8")
            outputs[str(path.relative_to(REPO_ROOT))] = content
        return outputs

    @staticmethod
    def _sanitize_id(incident_id: str) -> str:
        if not _SAFE_ID_RE.match(incident_id):
            # Fallback: hash anything suspicious so the file is still written safely
            hashed = hashlib.sha256(incident_id.encode("utf-8")).hexdigest()[:16]
            return f"unsafe-{hashed}"
        return incident_id

    @staticmethod
    def _render_one(inc: Incident) -> str:
        fm = (
            "---\n"
            f"incident_id: {inc.incident_id}\n"
            f"date: {inc.date:%Y-%m-%d}\n"
            f'title: "{inc.title}"\n'
            f"event:\n"
            f"  verification_status: {inc.event['verification_status']}\n"
            f"  lifecycle_phase: {inc.event['lifecycle_phase']}\n"
            f"  system_classification: {inc.event['system_classification']}\n"
            f"mechanism:\n"
            f"  root_cause_category: {inc.mechanism['root_cause_category']}\n"
            f"consequence:\n"
            f"  harm_domain: {inc.consequence['harm_domain']}\n"
            f"  temporality: {inc.consequence['temporality']}\n"
            f"  severity: {inc.consequence['severity']}\n"
            f"source_urls: {inc.source_urls}\n"
            f"views: {inc.views}\n"
            f"matched_entities: {inc.metadata.get('matched_entities', [])}\n"
            "---\n\n"
        )
        return fm + f"# {inc.title}\n\n{inc.summary}\n"


# ---------------------------------------------------------------------------
# Synthetic data for --dry-run (so CI can exercise the full pipeline)
# ---------------------------------------------------------------------------


def _synthetic_items() -> List[RawItem]:
    now = datetime(2026, 1, 1, tzinfo=timezone.utc)
    return [
        RawItem(
            source="synthetic",
            source_id="dry-run-001",
            url="https://example.com/openai-incident",
            title="Synthetic dry-run incident: OpenAI",
            snippet="Sample candidate generated by run_pipeline.py --dry-run.",
            published_at=now,
            language="en",
            metadata={
                "names": "OpenAI ChatGPT",
                "themes": "TECH_AUTOMATION",
            },
        ),
    ]


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main(argv: List[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Run the AI Incident pipeline.")
    parser.add_argument("--dry-run", action="store_true",
                        help="Skip source adapter, use synthetic data.")
    parser.add_argument("--since", type=str, default=None,
                        help="ISO-8601 datetime; default = 24 hours ago.")
    parser.add_argument("--limit", type=int, default=None,
                        help="Maximum number of incidents to write.")
    parser.add_argument("--enricher", type=str, default="rule",
                        choices=["rule", "llm"],
                        help="Enrichment backend: rule (default, free) or llm (costs API tokens).")
    args = parser.parse_args(argv)

    until = datetime.now(timezone.utc)
    if args.since:
        since = datetime.fromisoformat(args.since).replace(tzinfo=timezone.utc)
    else:
        since = until - timedelta(hours=24)
    print(f"Fetching incidents from {since.isoformat()} to {until.isoformat()}")

    if args.dry_run:
        raw: List[RawItem] = _synthetic_items()
        print(f"[dry-run] using {len(raw)} synthetic items")
    else:
        from scripts.source_gdelt_bigquery import GdeltBigQuerySource
        source: SourceAdapter = GdeltBigQuerySource()
        raw = source.fetch(since, until)
        print(f"[source] fetched {len(raw)} candidates since {since:%Y-%m-%d}")

        # Enrich raw items with scraped title + first paragraph
        from scripts.scraper import fetch_article
        enriched = 0
        for item in raw:
            article = fetch_article(item.url)
            if article:
                item.title = article.title
                item.snippet = article.first_paragraph
                enriched += 1
        print(f"[scraper] enriched {enriched} of {len(raw)} items")

    filter_engine: FilterEngine = WatchlistFilterEngine()

    if args.enricher == "llm":
        from scripts.enrich_llm import LLMEnricher
        enrich_pipe: EnrichPipe = LLMEnricher()
    else:
        enrich_pipe: EnrichPipe = RuleBasedEnricher()
    renderer: RenderAdapter = MarkdownRenderAdapter()

    candidates = filter_engine.filter(raw)
    print(f"[filter] {len(candidates)} candidates passed")

    incidents = enrich_pipe.enrich(candidates)
    print(f"[enrich] {len(incidents)} incidents classified")

    if args.limit is not None:
        incidents = incidents[:args.limit]
        print(f"[limit] capped to {args.limit} incidents")

    outputs = renderer.render(incidents)
    print(f"[render] wrote {len(outputs)} files to {INCIDENTS_DIR}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
